import axios from 'axios';
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const GET_COUNTRY_BY_ID = 'GET_COUNTRY_BY_ID';
export const SET_NAME = 'SET_NAME';
export const SET_PAGE = 'SET_PAGE';
export const FILTER_CONTINENT = 'FILTER_CONTINENT';
export const FILTER_CONTINENT = 'FILTER_CONTINENT';
export const ORDER_POPULATION = 'ORDER_POPULATION';
export const ORDER = 'ORDER';
